In [ ]:
                          ## ASSIGNMENT NO. 1

# Write a python program to create, append and remove etc.
# operation on Dictionary and Tuple.

## Dictionary Operations

list01 =["name", "age", "coure"]
list02 =["Disha","18", "CSE - CSF"]

my_dict = dict(zip(list01,list02))
print("Original Dictionary:", my_dict)

# Add an element
my_dict["city"] = "Bhopal,MP"
print("Addition:", my_dict)

# Update an element
my_dict["age"] = 19
print("Updating:", my_dict)

# Remove an element
my_dict.pop("city")
print("Removing:", my_dict)

# Accessing an element
print("Accessing an element:", my_dict["name"])

# Length of dictionary
X =len(my_dict)
print(X)


Original Dictionary: {'name': 'Disha', 'age': '18', 'coure': 'CSE - CSF'}
Addition: {'name': 'Disha', 'age': '18', 'coure': 'CSE - CSF', 'city': 'Bhopal,MP'}
Updating: {'name': 'Disha', 'age': 19, 'coure': 'CSE - CSF', 'city': 'Bhopal,MP'}
Removing: {'name': 'Disha', 'age': 19, 'coure': 'CSE - CSF'}
Accessing an element: Disha
3


In [ ]:
## Tuple Operations
my_tup = (1,2,3,4,5,6)
print("Original Tuple:",my_tup)

# Access an element
print("First element:", my_tup [0])

# Slicing
print("Sliced Tuple:", my_tup [-5:-2])

# Concatenation
num = (101,969,33)
new_tuple = my_tup  + num
print("After concatenation:", new_tuple)

# Repetition
print("Repeated Tuple:", (1, 2) * 0)

# Count
print("Count of 20:", my_tup .count(2))

# Find index
print("Index of 33:", my_tup .index(3))


Original Tuple: (1, 2, 3, 4, 5, 6)
First element: 1
Sliced Tuple: (2, 3, 4)
After concatenation: (1, 2, 3, 4, 5, 6, 101, 969, 33)
Repeated Tuple: ()
Count of 20: 1
Index of 33: 2


In [ ]:
                        ## ASSIGNMENT NO. 2

# Write a python program to find the largest of
# three numbers while implementing different forms of
# if..else statement.
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
c = int(input("Enter third number: "))

if a >= b and a >= c:
    largest = a
elif b >= a and b >= c:
    largest = b
else:
    largest = c

print("The largest number of the given three numbers is:", largest)

Enter first number: 8
Enter second number: 6
Enter third number: 5
The largest number of the given three numbers is: 8


In [ ]:
                          ## ASSIGNMENT NO. 3

# write a python program that accecpts length of sides of triangle
# as inputs and tells whether or not the triangle is
# right angled or not using functions

def R_tri (a,b,c):
    largest = max(a,b,c)

    if a==largest:
        if (b**2 + c**2 ==a**2):
            return True
    if b==largest:
        if (a**2 + c**2 ==b**2):
            return True
    if c==largest:
        if (a**2 + b**2 ==c**2):
            return True
    else:
        return False
print ("enter the three sides of triangle")
a = int(input("enter first side:"))
b = int(input("enter second side:"))
c = int(input("enter third side:"))

if R_tri (a,b,c):
    print ("it's a right angled triangle")

else:
    print ("it's NOT a right angled triangle")

enter the three sides of triangle
enter first side:5
enter second side:3
enter third side:2
it's NOT a right angled triangle


In [ ]:
                          ## ASSIGNMENT NO. 4

# Write a Python program to create an array
# perform addition of two matrices
# Using list and NumPy array

## Addition of two matrices using arrays
!pip install numpy
import numpy as np
print ("element= row(i), column(j)")

print("elements for array A:")
a1= int(input("a00: "))
a2= int(input("a01: "))
a3= int(input("a10: "))
a4= int(input("a11: "))
A= np.array([[a1,a2], [a3,a4]])

print("elements for array B:")
b1= int(input("b00: "))
b2= int(input("b01: "))
b3= int(input("b10: "))
b4= int(input("b11: "))
B= np.array([[b1,b2], [b3,b4]])

C=A+B

print("\nmatrix A = ")
print (A)
print("\nmatrix B =")
print (B)
print("\naddition matrix c =")
print (C)

element= row(i), column(j)
elements for array A:
a00: 6
a01: 5
a10: 0
a11: 3
elements for array B:
b00: 7
b01: 9
b10: 6
b11: 8

matrix A = 
[[6 5]
 [0 3]]

matrix B =
[[7 9]
 [6 8]]

addition matrix c =
[[13 14]
 [ 6 11]]


In [ ]:
## Addition of two matrices using list
matrix1 = [[1, 2], [3, 4]]
matrix2 = [[5, 6], [7, 8]]

result = []
for i in range(2):
    row = []
    for j in range(2):
        row.append(matrix1[i][j] + matrix2[i][j])
    result.append(row)

print("First matrix:", matrix1)
print("Second matrix:", matrix2)
print("Addition of matrices:", result)


First matrix: [[1, 2], [3, 4]]
Second matrix: [[5, 6], [7, 8]]
Addition of matrices: [[6, 8], [10, 12]]
